---
- name: Create gitea directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  become: yes
  become_user: "{{ gitea_podman_user }}"
  vars:
    ansible_common_remote_group: "{{ gitea_podman_group }}"
  loop:
    - "{{ gitea_podman_home }}/mariadb"
    - "{{ gitea_podman_home }}/data"
    - "{{ gitea_podman_home }}/config"
  register: mkdir

- name: Create directories owned by gitea
  ansible.builtin.shell: podman unshare chown 1000:1000 {{ item.path }}
  become: yes
  become_user: "{{ gitea_podman_user }}"
  vars:
    ansible_common_remote_group: "{{ gitea_podman_group }}"
  when: item.changed
  loop: "{{ mkdir.results }}"
  loop_control:
    label: "{{ item.path }}"

- name: Create gitea podman network
  containers.podman.podman_network:
    name: "{{ gitea_podman_network }}"
  become: yes
  become_user: "{{ gitea_podman_user }}"
  vars:
    ansible_common_remote_group: "{{ gitea_podman_group }}"
    
- name: Create gitea db container
  ansible.builtin.include_role:
    name: ahaydon.podman.podman_systemd
  vars:
    podman_systemd_name: "{{ gitea_podman_name }}-db"
    podman_systemd_user: "{{ gitea_podman_user }}"
    podman_systemd_image: docker.io/library/mariadb:{{ gitea_podman_db_version }}
    podman_systemd_network: gitea
    podman_systemd_environment:
      MARIADB_ROOT_PASSWORD: "{{ gitea_podman_mariadb_root_passwd }}"
      MARIADB_DATABASE: gitea
      MARIADB_USER: gitea
      MARIADB_PASSWORD: "{{ gitea_podman_db_passwd }}"
    podman_systemd_volumes:
      - "{{ gitea_podman_home }}/mariadb:/var/lib/mysql"
    podman_systemd_readonly: yes

- name: Create gitea web container
  ansible.builtin.include_role:
    name: ahaydon.podman.podman_systemd
  vars:
    podman_systemd_name: "{{ gitea_podman_name }}-web"
    podman_systemd_user: "{{ gitea_podman_user }}"
    podman_systemd_image: docker.io/gitea/gitea:{{ gitea_podman_version }}
    podman_systemd_network: gitea
    podman_systemd_environment:
      USER_UID: "{{ podman_user_uid }}"
      USER_GID: "{{ podman_user_gid }}"
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: gitea-db:3306
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: "{{ gitea_podman_db_passwd }}"
    podman_systemd_volumes:
      - "{{ gitea_podman_home }}/data:/var/lib/gitea"
      - "{{ gitea_podman_home }}/config:/etc/gitea"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    podman_systemd_ports:
      - 3000:3000
      - 2222:2222

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable gitea service
  ansible.builtin.systemd:
    name: container-{{ gitea_podman_name }}-{{ item }}.service
    enabled: yes
  become: yes
  loop:
    - db
    - web

- name: Start gitea service
  ansible.builtin.systemd:
    name: container-{{ gitea_podman_name }}-{{ item }}.service
    state: started
  become: yes
  loop:
    - db
    - web

